spring:
  datasource:
    url: jdbc:h2:mem:testdb
  h2:
    console:
      enabled: true

logging:
  level:
    com.ashu.practice.mapper: TRACE

mybatis:
  config-location: classpath:mybatis-config.xml